### PR TITLE
Exported MessageXFragment interface

### PR DESCRIPTION
**Pull request by nlapshin**
Have some problems with using interface

`Return type of public method from exported class has or is using name 'MessageXFragment' from external module`

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
The type is internal and should ideally stay that way.

Which code causes the problem?

**Comment by nlapshin** [comment]
This interface is exported and used everywhere(ctx.reply, for example)

`export declare type MessageX = MessageXFragment & Message;`

Also plugin don't export MessageX from main types file, but MessageX type can used for describe types inside application

**Comment by KnorpelSenf** [comment]
We can consider exporting `MessageX` and similar types. I still see no point in exporting the parts of which it is composed.

**Comment by nlapshin** [comment]
Unfortunately, It cat lead to typescript errors. I implemented example in which case i catch this error. This is not exactly the code of my project, just an example.

`import { Bot, Context } from 'grammy'
import { hydrate, HydrateFlavor } from '@grammyjs/hydrate'

export type IContext = HydrateFlavor<Context>

export class Reply {
  async replyWrap(ctx: IContext, reply: string) {
    console.log('before')

    const res = await ctx.reply(reply)

    console.log('after')

    return res
  }
}

const bot = new Bot<IContext>('token')
bot.use(hydrate)

const reply = new Reply()

bot.on('message', async (ctx: IContext) => {
  await reply.replyWrap(ctx, 'messages')
})
`

https://github.com/nlapshin/grammy-test/blob/main/index.ts

**Comment by KnorpelSenf** [comment]
Would exporting `MessageX` mitigate this?

**Comment by nlapshin** [comment]
No, typescript resolve MessageX as MessageXFragment & Message

**Comment by KnorpelSenf** [comment]
I see.

If anything, we should be consistent, and export all fragments of all files. Otherwise someone will open the same issue for a differnet API call :)

Let me quickly fix this up.

**Pull request merged**
