### PR TITLE
chore: new deno fmt rules

### PR DESCRIPTION
**Pull request by roziscoding**
`lineWidth` changed to `120` and `indentWidth` changed to the default value

### CODE REVIEW

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
Could you just indent width 4 in order not to change everything?

**Comment by roziscoding** [comment]
Since this is the only thing that's really being changed with this PQ, I'd rather just go forward with it, I don't see harm in touching all the files.

**Comment by KnorpelSenf** [comment]
It's just strange to do it different from the core lib and all other plugins (are there exceptions by now that use 2 spaces?)

**Comment by roziscoding** [comment]
> It's just strange to do it differently from the core lib and all other plugins (are there exceptions by now that use 2 spaces?)

I'd assumed all other code would use 2 spaces. The commands plugin does.
If that's the default for official code, I can stick with it, regardless of personal opinion.

**Comment by roziscoding** [comment]
Since we're sticking with core, this PR doesn't make sense anymore. Core uses the default `lineWidth`.

**Pull request closed without merging**
