### PR TITLE
[Half asleep PQ] Avoid intersection, use replace strategy

### PR DESCRIPTION
**Pull request by KnightNiwrem**
Maybe expect bugs.

Compiles with the following snippet:
```typescript
import { Bot, type Context } from 'grammy';
import { bold, fmt, hydrateReply, italic, link, type ParseModeContext } from '@grammyjs/parse-mode';
import { hydrate, type HydrateFlavor } from '@grammyjs/hydrate';

type MyContext = ParseModeContext<HydrateFlavor<Context>>;

const bot = new Bot<MyContext>('');

function wait(timeout: number) {
  const timeoutPromise = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(true);
    }, timeout);
  });
  return timeoutPromise;
}

bot.use(hydrate(), hydrateReply, async ctx => {
  const first = await ctx.replyWithMarkdownV2("*Ehh*");
  await wait(1000);
  await first.delete();
  const second = await ctx.replyFmt(fmt`${bold('bold!')}
${bold(italic('bitalic!'))}
${bold(fmt`bold ${link('blink', 'example.com')} bold`)}`);
  await wait(1000);
  await second.delete();
});

bot.start();
```

Or if with https://github.com/grammyjs/emoji/tree/compat-flavor, then this compiles too:
```typescript
import { Bot, type Context } from 'grammy';
import { EmojiFlavor, emojiParser } from '@grammyjs/emoji';
import { hydrate, type HydrateFlavor } from '@grammyjs/hydrate';
import { bold, fmt, hydrateReply, italic, link, type ParseModeContext } from '@grammyjs/parse-mode';

type MyContext = ParseModeContext<EmojiFlavor<HydrateFlavor<Context>>>;

const bot = new Bot<MyContext>('');

function wait(timeout: number) {
  const timeoutPromise = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(true);
    }, timeout);
  });
  return timeoutPromise;
}

bot.use(hydrate(), emojiParser(), hydrateReply, async ctx => {
  const first = await ctx.replyWithMarkdownV2("*Ehh*");
  await wait(1000);
  await first.delete();

  const second = await ctx.replyFmt(fmt`${bold('bold!')}
${bold(italic('bitalic!'))}
${bold(fmt`bold ${link('blink', 'example.com')} bold`)}`);
  await wait(1000);
  await second.delete();

  const third = await ctx.replyWithEmoji`Hi! ${"robot"}`;
  await wait(1000);
  await third.delete();
});

bot.start();

```

Pending questions:
- [x] Is this breaking?

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
This is genius. And you were half asleep while coding it? I'm wondering what you can do when you're fully asleep!

I found no bugs. The idea of simply merging the objects, composing them as we like, looks cool. I would still like to have other people confirm on their existing code bases that this is not a breaking change.

**Comment by KnorpelSenf** [comment]
> Or if with [https://github.com/grammyjs/emoji/tree/compat-flavor](https://github.com/grammyjs/emoji/tree/compat-flavor?rgh-link-date=2022-04-01T15%3A35%3A55Z), then this compiles too:

Also, how is this not a PQ yet? /cc @andrrms

**Comment by andrrms** [comment]
Sorry the late guys! 😅
I've tested it and, while it works, I've noticed that you need to use `HydrateFlavor` first in order to provide context-awareness to other plugins too.
```typescript
type MyContext = ParseModeContext<EmojiFlavor<HydrateFlavor<Context>>>; // works fine
type MyContext = HydrateFlavor<ParseModeContext<EmojiFlavor<Context>>>; // only default grammY methods will get context-awareness methods
```
But you managed to get here with a lot of effort, nothing that a warning in the documentation can't solve!

**Comment by KnorpelSenf** [comment]
It actually makes quite a lot of sense that the order matters. The docs will need to be updated. @roj1512 would you know what changes need to be performed here? Otherwise I don't mind writing it

**Review by KnorpelSenf — APPROVED** [review]
LGTM!

**Pull request merged**
